/* AE64 Pro Control: WebHID configuration UI for the AE64 Pro vendor collection. */
const STORAGE_KEY = "ae64-pro-control-profile-v1";
const layout = [
  [{n:"Esc"},{n:"1"},{n:"2"},{n:"3"},{n:"4"},{n:"5"},{n:"6"},{n:"7"},{n:"8"},{n:"9"},{n:"0"},{n:"-"},{n:"="},{n:"Backspace",u:2}],
  [{n:"Tab",u:1.5},{n:"Q"},{n:"W"},{n:"E"},{n:"R"},{n:"T"},{n:"Y"},{n:"U"},{n:"I"},{n:"O"},{n:"P"},{n:"["},{n:"]"},{n:"\\",u:1.5}],
  [{n:"Caps Lock",u:1.75},{n:"A"},{n:"S"},{n:"D"},{n:"F"},{n:"G"},{n:"H"},{n:"J"},{n:"K"},{n:"L"},{n:";"},{n:"'"},{n:"Enter",u:2.25}],
  [{n:"Shift",u:2},{n:"Z"},{n:"X"},{n:"C"},{n:"V"},{n:"B"},{n:"N"},{n:"M"},{n:","},{n:"."},{n:"/"},{n:"Shift"},{n:"↑"},{n:"Del"}],
  [{n:"Ctrl",u:1.25},{n:"Win",u:1.25},{n:"Alt",u:1.25},{n:"Space",u:6.25},{n:"Alt"},{n:"Fn"},{n:"←"},{n:"↓"},{n:"→"}]
];
// The AE64 firmware addresses the five keymap rows as 1–5 (not the UI's 0–4).
// Keeping both values prevents a visual row index from being used as a HID row.
const keys = layout.flatMap((row, rowIndex) => row.map((key, colIndex) => ({...key, u:key.u || 1, id:0, row:rowIndex, protocolRow:rowIndex+1, col:colIndex}))).map((key, index) => ({...key, id:index}));
function isFnKey(key){return key.n==="Fn"}
function defaultMapping(key){const aliases={Esc:"Escape",Del:"Delete","←":"Left Arrow","↓":"Down Arrow","↑":"Up Arrow","→":"Right Arrow","Caps Lock":"Caps Lock",Backspace:"Backspace",Tab:"Tab",Enter:"Enter",Space:"Space"};if(key.row===3&&key.col===0)return "Left Shift";if(key.row===3&&key.col===11)return "Right Shift";if(key.row===4&&key.col===0)return "Left Ctrl";if(key.row===4&&key.col===1)return "Left Win";if(key.row===4&&key.col===2)return "Left Alt";if(key.row===4&&key.col===4)return "Right Alt";return aliases[key.n]||key.n}
const defaultProfile = () => ({schema:2,selected:14,travel:Object.fromEntries(keys.map(k=>[k.id,2])), rapid:Object.fromEntries(keys.map(k=>[k.id,{enabled:false,press:.15,release:.15}])), mapping:Object.fromEntries(keys.map(k=>[k.id,defaultMapping(k)]))});
const hardware = { performance:new Map(), keycodes:new Map(), info:null, feature:null, precision:null };
const dirty = { performance:new Set(), mapping:new Set() };
let profile = loadProfile(), page = "overview", transport = null, toastTimer;
function loadProfile(){const defaults=defaultProfile();try{const stored=JSON.parse(localStorage.getItem(STORAGE_KEY));if(!stored)return defaults;const mapping=Object.fromEntries(keys.map(key=>{const value=stored.mapping?.[key.id];return[key.id,!value||value===key.n?defaultMapping(key):value]}));return {...defaults,...stored,schema:2,travel:{...defaults.travel,...stored.travel},rapid:{...defaults.rapid,...stored.rapid},mapping}}catch{return defaults}}
function selected(){return keys.find(k=>k.id===Number(profile.selected)) || keys[0]}
function markDirty(kind,id=selected().id){dirty[kind].add(id)}
function hasDirty(){return dirty.performance.size>0||dirty.mapping.size>0}
function keyPosition(id){const key=keys.find(k=>k.id===Number(id));if(!key)throw new Error("Unknown keyboard key.");return {row:key.protocolRow,col:key.col}}
// Build without mutating the key objects used as state.
function boardHtml(className=""){let cursor=0;return `<div class="keyboard ${className}">${layout.map(row=>`<div class="keyboard-row">${row.map(key=>{const k=keys[cursor++];return `<button class="key ${k.id===Number(profile.selected)?"selected":""}" style="--u:${k.u}" data-key="${k.id}" type="button"><span>${k.n}</span><small class="mapped">${profile.mapping[k.id]||k.n}</small></button>`}).join("")}</div>`).join("")}</div>`}
function miniBoard(){let cursor=0;return `<div class="keyboard" style="--unit:clamp(21px,2.45vw,38px);margin:0">${layout.map(row=>`<div class="keyboard-row">${row.map(key=>{const k=keys[cursor++];return `<span class="key ${[14,29,44].includes(k.id)?"selected":""}" style="--u:${k.u}"><span>${k.n}</span></span>`}).join("")}</div>`).join("")}</div>`}
function mountHero(){document.querySelector("#heroKeyboard").innerHTML=miniBoard()}
function openWorkspace(target="overview"){document.querySelector("main").classList.add("hidden");document.querySelector(".topbar").classList.add("hidden");document.querySelector("#workspace").classList.remove("hidden");page=target;render();window.scrollTo({top:0,behavior:"smooth"})}
function returnHome(){document.querySelector("#workspace").classList.add("hidden");document.querySelector("main").classList.remove("hidden");document.querySelector(".topbar").classList.remove("hidden");window.scrollTo({top:0,behavior:"smooth"})}
function pageCopy(){return {overview:["Tổng quan","Chọn một phím trên bàn phím để bắt đầu."],travel:["Travel distance","Chỉnh điểm kích hoạt cho phím đang chọn."],rapid:["Rapid Trigger","Thiết lập độ nhạy nhấn và nhả trên từng phím."],mapping:["Key mapping","Gán chức năng cơ bản cho phím đang chọn."]}[page]}
function currentKeySummary(){const k=selected();return `<div class="key-summary"><span>PHÍM ĐANG CHỌN</span><strong>${k.n}</strong></div>`}
function boardPanel(){return `<section class="panel board-panel"><div><h2>Keyboard layout</h2><p>Nhấn vào một phím để chọn. Kích thước keycap hiển thị theo đơn vị u.</p></div><div class="keyboard-wrap">${boardHtml()}</div><div class="board-footer"><span>Đã chọn: <b class="selected-name">${selected().n}</b></span><span>Compact ANSI layout</span></div></section>`}
function overviewPage(){const rapidCount=Object.values(profile.rapid).filter(x=>x.enabled).length;const status=transport?.connected?`Đã kết nối · firmware ${hardware.info?.firmware||"đang đọc"}`:"Bản cấu hình cục bộ";return `<div class="page-grid"><section class="panel overview-card"><h2>AE64 Pro workspace</h2><p>${transport?.connected?"Các report HID đã xác thực đang sẵn sàng. Lưu thay đổi để ghi các phím đã chỉnh vào bàn phím.":"Kết nối bàn phím để đọc và ghi cấu hình qua WebHID; bản demo vẫn được lưu trong trình duyệt."}</p><ul><li><span>Device ID</span><strong>1CA6:300A</strong></li><li><span>Trạng thái</span><strong>${status}</strong></li><li><span>Rapid Trigger</span><strong>${rapidCount} phím bật</strong></li></ul></section>${boardPanel()}<section class="panel"><h3>Phím đang chọn</h3>${currentKeySummary()}<p>Chuyển sang Travel distance, Rapid Trigger hoặc Key mapping để chỉnh nhanh phím này.</p><div class="apply-row"><button class="button primary" data-goto="travel" type="button">Cấu hình phím</button></div></section></div>`}
function travelPage(){const k=selected(),value=Number(profile.travel[k.id]||2).toFixed(2);return `<div class="page-grid">${boardPanel()}<section class="panel control-card"><h2>Actuation point</h2>${currentKeySummary()}<label class="field"><span>Travel distance</span><div class="range-row"><input id="travelRange" type="range" min="0.10" max="4" step="0.01" value="${value}"><input class="number" id="travelNumber" type="number" min="0.10" max="4" step="0.01" value="${value}"></div><p class="help">Phím sẽ nhận thao tác khi được nhấn đến ${value} mm. Phạm vi 0.10 – 4.00 mm.</p></label><div class="apply-row"><button class="button ghost" data-all-travel type="button">Áp dụng cho tất cả</button><button class="button primary" data-save-local type="button">Lưu thay đổi</button></div></section></div>`}
function rapidPage(){const k=selected(),v=profile.rapid[k.id]||{enabled:false,press:.15,release:.15};return `<div class="page-grid">${boardPanel()}<section class="panel control-card"><h2>Rapid Trigger</h2>${currentKeySummary()}<div class="switch-row"><div><h3>Bật Rapid Trigger</h3><p>Phím reset ngay khi di chuyển theo chiều ngược lại.</p></div><input class="toggle" id="rapidEnabled" type="checkbox" ${v.enabled?"checked":""}></div><label class="field"><span>Điểm nhận (press)</span><div class="range-row"><input id="pressRange" type="range" min="0.01" max="2" step="0.01" value="${v.press}"><input class="number" id="pressNumber" type="number" min="0.01" max="2" step="0.01" value="${v.press}"></div></label><label class="field"><span>Điểm nhả (release)</span><div class="range-row"><input id="releaseRange" type="range" min="0.01" max="2" step="0.01" value="${v.release}"><input class="number" id="releaseNumber" type="number" min="0.01" max="2" step="0.01" value="${v.release}"></div><p class="help">Các giá trị này chỉ được giữ trong cấu hình trình duyệt cho đến khi có giao thức HID AE64 Pro đã xác thực.</p></label><div class="apply-row"><button class="button ghost" data-all-rapid type="button">Áp dụng cho tất cả</button><button class="button primary" data-save-local type="button">Lưu thay đổi</button></div></section></div>`}
const mappings=["A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z","1","2","3","4","5","6","7","8","9","0","-","=","[","]","\\",";","'",",",".","/","Enter","Escape","Tab","Space","Backspace","Delete","Caps Lock","Left Arrow","Down Arrow","Up Arrow","Right Arrow","Left Ctrl","Left Shift","Left Alt","Left Win","Right Shift","Right Alt","Unassigned"];
const HID_CODES=Object.fromEntries([...["A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z"].map((label,index)=>[label,4+index]),...["1","2","3","4","5","6","7","8","9","0"].map((label,index)=>[label,30+index]),["-",45],["=",46],["[",47],["]",48],["\\",49],[";",51],["'",52],[",",54],[".",55],["/",56],["Caps Lock",57],["Enter",40],["Escape",41],["Backspace",42],["Tab",43],["Space",44],["Delete",76],["Right Arrow",79],["Left Arrow",80],["Down Arrow",81],["Up Arrow",82],["Left Ctrl",224],["Left Shift",225],["Left Alt",226],["Left Win",227],["Right Shift",229],["Right Alt",230],["Unassigned",0]]);
const HID_LABELS=Object.fromEntries(Object.entries(HID_CODES).map(([label,code])=>[code,label]));
function mappingPage(){const k=selected(),fnKey=isFnKey(k),value=profile.mapping[k.id]||defaultMapping(k),choices=fnKey?["Fn"]:mappings;return `<div class="page-grid">${boardPanel()}<section class="panel control-card"><h2>Gán phím</h2>${currentKeySummary()}<label class="field"><span>Chức năng mới</span><select class="mapping-choice" id="mappingSelect" ${fnKey?"disabled":""}>${choices.map(x=>`<option ${x===value?"selected":""}>${x}</option>`).join("")}</select><p class="help">${fnKey?"Fn là chức năng nội bộ của firmware, không phải HID keyboard usage; driver giữ nguyên mapping trên bàn phím.":"Các mapping HID cơ bản được lưu theo profile cục bộ và hiển thị dưới keycap."}</p></label><div class="apply-row"><button class="button ghost" data-reset-key type="button" ${fnKey?"disabled":""}>Khôi phục mặc định</button><button class="button primary" data-save-local type="button">Lưu mapping</button></div></section></div>`}
function render(){const [title,desc]=pageCopy();document.querySelector("#pageTitle").textContent=title;document.querySelector("#pageDescription").textContent=desc;document.querySelectorAll("#sideNav button").forEach(b=>b.classList.toggle("active",b.dataset.page===page));document.querySelector("#pageContent").innerHTML=page==="overview"?overviewPage():page==="travel"?travelPage():page==="rapid"?rapidPage():mappingPage();bindPage()}
function bindPage(){document.querySelectorAll("[data-key]").forEach(btn=>btn.addEventListener("click",()=>selectKey(Number(btn.dataset.key))));document.querySelectorAll("[data-goto]").forEach(btn=>btn.addEventListener("click",()=>{page=btn.dataset.goto;render()}));const sync=(a,b,onChange)=>{const A=document.querySelector(a),B=document.querySelector(b);if(!A||!B)return;const update=(source,target)=>{target.value=source.value;onChange(Number(source.value))};A.addEventListener("input",()=>update(A,B));B.addEventListener("input",()=>update(B,A))};if(page==="travel"){sync("#travelRange","#travelNumber",v=>{profile.travel[selected().id]=v;markDirty("performance")});document.querySelector("[data-all-travel]").onclick=()=>{const v=profile.travel[selected().id];keys.forEach(k=>{profile.travel[k.id]=v;markDirty("performance",k.id)});showToast("Đã áp dụng travel distance cho mọi phím.")}}if(page==="rapid"){const state=()=>profile.rapid[selected().id]||(profile.rapid[selected().id]={enabled:false,press:.15,release:.15});document.querySelector("#rapidEnabled").addEventListener("change",e=>{state().enabled=e.target.checked;markDirty("performance")});sync("#pressRange","#pressNumber",v=>{state().press=v;markDirty("performance")});sync("#releaseRange","#releaseNumber",v=>{state().release=v;markDirty("performance")});document.querySelector("[data-all-rapid]").onclick=()=>{const value={...state()};keys.forEach(k=>{profile.rapid[k.id]={...value};markDirty("performance",k.id)});showToast("Đã áp dụng Rapid Trigger cho mọi phím.")}}if(page==="mapping"){const mappingSelect=document.querySelector("#mappingSelect");if(!mappingSelect.disabled)mappingSelect.addEventListener("change",e=>{profile.mapping[selected().id]=e.target.value;markDirty("mapping")});document.querySelector("[data-reset-key]").onclick=()=>{profile.mapping[selected().id]=defaultMapping(selected());markDirty("mapping");render();showToast("Đã khôi phục mapping mặc định.")}}document.querySelectorAll("[data-save-local]").forEach(b=>b.addEventListener("click",saveLocal))}
function selectKey(id){profile.selected=id;render();readSelectedFromKeyboard().catch(error=>showToast(error.message))}
async function saveLocal(){let message="Đã lưu cấu hình trong trình duyệt.";if(transport?.connected&&hasDirty()){try{await writeDirtyChanges();message="Đã ghi và lưu vĩnh viễn thay đổi vào bộ nhớ AE64 Pro."}catch(error){message=`Chưa thể lưu vào bàn phím: ${error.message}. Bản sao chỉ được giữ trong trình duyệt.`}}localStorage.setItem(STORAGE_KEY,JSON.stringify(profile));document.querySelector("#saveNotice").textContent=message;document.querySelector("#saveNotice").classList.remove("hidden");showToast(message)}
function showToast(message){const node=document.querySelector("#toast");node.textContent=message;node.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>node.classList.remove("show"),2800)}
function performanceForKey(id){const saved=hardware.performance.get(id)||{};const rapid=profile.rapid[id]||{enabled:false,press:.15,release:.15};return {...saved,mode:rapid.enabled?1:0,normalPress:Number(profile.travel[id]||2),rtFirstTouch:rapid.enabled?(saved.rtFirstTouch||Number(profile.travel[id]||2)):0,rtPress:rapid.enabled?Number(rapid.press):0,rtRelease:rapid.enabled?Number(rapid.release):0}}
async function readSelectedFromKeyboard(){if(!transport?.connected)return;const id=selected().id;if(dirty.performance.has(id)&&dirty.mapping.has(id))return;const position=keyPosition(id);const [performance,keycode]=await Promise.all([transport.getPerformance(position),transport.getKeyCode(position)]);hardware.performance.set(id,performance);hardware.keycodes.set(id,keycode.keycode);if(!dirty.performance.has(id)){profile.travel[id]=performance.normalPress||profile.travel[id];profile.rapid[id]={enabled:performance.mode===1,press:performance.rtPress||.15,release:performance.rtRelease||.15}}if(!dirty.mapping.has(id)&&HID_LABELS[keycode.keycode])profile.mapping[id]=HID_LABELS[keycode.keycode];if(selected().id===id)render()}
async function writeDirtyChanges(){const performanceIds=[...dirty.performance];const mappingIds=[...dirty.mapping];for(const id of performanceIds){await transport.setPerformance(keyPosition(id),performanceForKey(id));hardware.performance.set(id,performanceForKey(id))}for(const id of mappingIds){const label=profile.mapping[id];const keycode=HID_CODES[label];if(keycode===undefined)throw new Error(`${label} không có HID keyboard usage hợp lệ.`);await transport.setKeyCode(keyPosition(id),keycode);hardware.keycodes.set(id,keycode)}if(performanceIds.length)await transport.saveParameters(2);if(mappingIds.length)await transport.saveParameters(4);performanceIds.forEach(id=>dirty.performance.delete(id));mappingIds.forEach(id=>dirty.mapping.delete(id))}
async function connect(){if(!("hid" in navigator)){showToast("Trình duyệt này chưa hỗ trợ WebHID. Hãy dùng Chrome hoặc Edge.");return}try{const devices=await navigator.hid.requestDevice({filters:AE64HidTransport.filters});const device=devices[0];if(!device){showToast("Chưa chọn thiết bị nào.");return}transport=new AE64HidTransport(device);await transport.open();const [info,feature,precision]=await Promise.all([transport.getDeviceInfo(),transport.getDeviceFeature(),transport.getRtPrecision()]);hardware.info=info;hardware.feature=feature;hardware.precision=precision;document.querySelector("#connectionLabel").textContent=`Đã kết nối · FW ${info.firmware}`;openWorkspace();await readSelectedFromKeyboard();showToast(`Đã kết nối AE64 Pro · firmware ${info.firmware} · RT precision ${precision.toFixed(3)} mm.`)}catch(error){if(transport)transport.close().catch(()=>{});transport=null;showToast(`Không thể kết nối: ${error.message}`)}}
function exportProfile(){const blob=new Blob([JSON.stringify({device:"Everglide AE64 Pro",vid:"1CA6",pid:"300A",savedAt:new Date().toISOString(),profile},null,2)],{type:"application/json"});const link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download="ae64-pro-profile.json";link.click();URL.revokeObjectURL(link.href);showToast("Đã xuất tệp cấu hình JSON.")}
document.querySelectorAll("#demoButton,#heroStart,#heroDemo").forEach(b=>b.addEventListener("click",()=>openWorkspace()));document.querySelector("#connectButton").addEventListener("click",connect);document.querySelector("#workspaceConnectButton").addEventListener("click",connect);document.querySelector("#backHomeButton").addEventListener("click",returnHome);document.querySelector("#sideNav").addEventListener("click",e=>{const b=e.target.closest("button[data-page]");if(b){page=b.dataset.page;render()}});document.querySelector("#saveButton").addEventListener("click",saveLocal);document.querySelector("#exportButton").addEventListener("click",exportProfile);mountHero();
