"use strict";

/* AE64 Pro Control — local-first UI for the reverse-engineered WebHID protocol. */
const { AE64HidTransport, SAVE_GROUP, MATRIX_ROWS, MATRIX_COLS } = window.AE64Protocol;
const STORAGE_KEY = "ae64-control-workspace-v3";
const LANGUAGE_KEY = "ae64-control-language";

const layout = [
  [{n:"Esc"},{n:"1"},{n:"2"},{n:"3"},{n:"4"},{n:"5"},{n:"6"},{n:"7"},{n:"8"},{n:"9"},{n:"0"},{n:"-"},{n:"="},{n:"Backspace",u:2}],
  [{n:"Tab",u:1.5},{n:"Q"},{n:"W"},{n:"E"},{n:"R"},{n:"T"},{n:"Y"},{n:"U"},{n:"I"},{n:"O"},{n:"P"},{n:"["},{n:"]"},{n:"\\",u:1.5}],
  [{n:"Caps",u:1.75},{n:"A"},{n:"S"},{n:"D"},{n:"F"},{n:"G"},{n:"H"},{n:"J"},{n:"K"},{n:"L"},{n:";"},{n:"'"},{n:"Enter",u:2.25}],
  [{n:"Shift",u:2},{n:"Z"},{n:"X"},{n:"C"},{n:"V"},{n:"B"},{n:"N"},{n:"M"},{n:","},{n:"."},{n:"/"},{n:"Shift"},{n:"↑"},{n:"Del"}],
  [{n:"Ctrl",u:1.25},{n:"Win",u:1.25},{n:"Alt",u:1.25},{n:"Space",u:6.25},{n:"Alt"},{n:"Fn"},{n:"←"},{n:"↓"},{n:"→"}],
];

// The five physical rows are addressed as 1–5 by the AE64 firmware.
const keys = layout.flatMap((row, uiRow) => row.map((key, col) => ({...key,u:key.u||1,uiRow,row:uiRow+1,col}))).map((key,id)=>({...key,id}));
const KEYCODE_GROUPS = {
  keyboard: [
    ..."ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("").map((label,index)=>({label,code:4+index})),
    ..."1234567890".split("").map((label,index)=>({label,code:30+index})),
    ["Enter",40],["Escape",41],["Backspace",42],["Tab",43],["Space",44],["-",45],["=",46],["[",47],["]",48],["\\",49],[";",51],["'",52],[",",54],[".",55],["/",56],["Caps Lock",57],
    ...Array.from({length:12},(_,index)=>[`F${index+1}`,58+index]),
    ["Print Screen",70],["Scroll Lock",71],["Pause",72],["Insert",73],["Home",74],["Page Up",75],["Delete",76],["End",77],["Page Down",78],["Right Arrow",79],["Left Arrow",80],["Down Arrow",81],["Up Arrow",82],
    ["Left Ctrl",224],["Left Shift",225],["Left Alt",226],["Left Win",227],["Right Ctrl",228],["Right Shift",229],["Right Alt",230],["Right Win",231],["Unassigned",0],
  ].map((item)=>Array.isArray(item)?{label:item[0],code:item[1]}:item),
  media: [["Play / Pause",0x00cd],["Next Track",0x00b5],["Previous Track",0x00b6],["Stop",0x00b7],["Mute",0x00e2],["Volume Up",0x00e9],["Volume Down",0x00ea],["Calculator",0x0192],["Browser Home",0x0223],["Browser Back",0x0224],["Browser Forward",0x0225]].map(([label,code])=>({label,code})),
  mouse: [["Mouse Left",0x0101],["Mouse Right",0x0102],["Mouse Middle",0x0104],["Mouse Forward",0x0108],["Mouse Back",0x0110]].map(([label,code])=>({label,code})),
  firmware: [["Fn layer 1",0xf001],["Fn layer 2",0xf002],["Fn layer 3",0xf003],["Lighting toggle",0xf010],["Lighting mode +",0xf011],["Brightness +",0xf012],["Brightness -",0xf013]].map(([label,code])=>({label,code})),
};
const KEYCODES = Object.values(KEYCODE_GROUPS).flat();
const KEYCODE_LABELS = new Map(KEYCODES.map((entry)=>[entry.code,entry.label]));

const FALLBACK_TRANSLATIONS = {
  en:{languageName:"English",brandTagline:"Independent WebHID driver",navFeatures:"Features",navProtocol:"Protocol",language:"Language",openDemo:"Open demo",connectKeyboard:"Connect keyboard",heroEyebrow:"LOCAL-FIRST · NO CHINA ROUND TRIP",heroLine1:"Your AE64.",heroLine2:"Fully visible.",heroLead:"Configure actuation, Rapid Trigger, remaps, RGB, profiles and the keyboard's hidden diagnostic controls directly through WebHID.",exploreOffline:"Explore offline",compatibility:"Desktop Chrome or Edge · HTTPS or localhost · no account required",ready:"READY",deviceId:"Device ID",reportSize:"Report size",collection:"Collection",featurePerformanceTitle:"Hall performance",featurePerformanceBody:"Per-key actuation, RT, independent press/release values and both dead zones.",featureKeymapTitle:"Four key layers",featureKeymapBody:"Keyboard, media, mouse, lighting and internal firmware functions.",featureHiddenTitle:"Feature Lab",featureHiddenBody:"Calibration, raw travel, magnetic-axis metadata and advanced-key inspection stay visible.",protocolEyebrow:"CAPTURE-DERIVED, DEVICE-LOCAL",protocolTitle:"The keyboard is the source of truth.",protocolBody:"The driver reads the current hardware record before editing, preserves firmware-owned fields, writes only staged changes, commits the correct parameter group, and reads important values back. Firmware flashing is intentionally excluded.",offlineWorkspace:"Offline workspace",overview:"Overview",performance:"Performance",keymap:"Key mapping",lighting:"Lighting",settings:"Device settings",featureLab:"Feature Lab",diagnostics:"Diagnostics",stagedEdits:"Staged edits",stagedEditsBody:"Nothing reaches the keyboard until Apply.",profile:"Profile",layer:"Layer",home:"Home",connect:"Connect",revert:"Revert",applyChanges:"Apply changes",offline:"Offline",noPendingChanges:"No pending changes"},
  vi:{languageName:"Tiếng Việt",brandTagline:"Trình điều khiển WebHID độc lập",navFeatures:"Tính năng",navProtocol:"Giao thức",language:"Ngôn ngữ",openDemo:"Mở bản thử",connectKeyboard:"Kết nối bàn phím",heroEyebrow:"CỤC BỘ TRƯỚC · KHÔNG CHỜ MÁY CHỦ TRUNG QUỐC",heroLine1:"AE64 của bạn.",heroLine2:"Hiển thị đầy đủ.",heroLead:"Thiết lập hành trình, Rapid Trigger, ánh xạ phím, RGB, hồ sơ và các điều khiển chẩn đoán ẩn qua WebHID.",exploreOffline:"Khám phá ngoại tuyến",compatibility:"Chrome hoặc Edge máy tính · HTTPS hoặc localhost · không cần tài khoản",ready:"SẴN SÀNG",deviceId:"Mã thiết bị",reportSize:"Kích thước báo cáo",collection:"Collection",featurePerformanceTitle:"Hiệu năng Hall",featurePerformanceBody:"Điểm nhận phím, RT, nhấn/nhả và vùng chết riêng cho từng phím.",featureKeymapTitle:"Bốn lớp phím",featureKeymapBody:"Bàn phím, media, chuột, đèn và chức năng firmware nội bộ.",featureHiddenTitle:"Phòng thí nghiệm",featureHiddenBody:"Luôn hiển thị cân chỉnh, hành trình thô, dữ liệu trục từ và chế độ phím nâng cao.",protocolEyebrow:"TỪ BẢN GHI GÓI TIN · CHẠY CỤC BỘ",protocolTitle:"Bàn phím là nguồn dữ liệu chuẩn.",protocolBody:"Trình điều khiển đọc dữ liệu hiện tại trước khi sửa, giữ nguyên trường do firmware quản lý, chỉ ghi thay đổi đã xếp hàng, lưu đúng nhóm tham số và đọc lại giá trị quan trọng. Cập nhật firmware bị loại trừ có chủ ý.",offlineWorkspace:"Không gian ngoại tuyến",overview:"Tổng quan",performance:"Hiệu năng",keymap:"Ánh xạ phím",lighting:"Ánh sáng",settings:"Cài đặt thiết bị",featureLab:"Phòng thí nghiệm",diagnostics:"Chẩn đoán",stagedEdits:"Thay đổi tạm",stagedEditsBody:"Không có gì được ghi cho đến khi nhấn Áp dụng.",profile:"Hồ sơ",layer:"Lớp",home:"Trang đầu",connect:"Kết nối",revert:"Hoàn tác",applyChanges:"Áp dụng",offline:"Ngoại tuyến",noPendingChanges:"Không có thay đổi chờ"},
};

const defaultPerformance=()=>({mode:0,normalPress:2,normalRelease:0,rtFirstTouch:2,rtPress:.15,rtRelease:.15,pressDeadStroke:.1,releaseDeadStroke:.1,axis:0,calibrate:0,axisV2Id:0,axisRangeMax:0,axisCoefficient:0});
function defaultKeycode(key){
  const aliases={Esc:41,Backspace:42,Tab:43,Caps:57,Enter:40,Del:76,"←":80,"↓":81,"↑":82,"→":79,Space:44};
  if(key.uiRow===3&&key.col===0)return 225;if(key.uiRow===3&&key.col===11)return 229;if(key.uiRow===4&&key.col===0)return 224;if(key.uiRow===4&&key.col===1)return 227;if(key.uiRow===4&&key.col===2)return 226;if(key.uiRow===4&&key.col===4)return 230;if(key.n==="Fn")return 0xf001;
  return aliases[key.n]??KEYCODES.find((entry)=>entry.label===key.n)?.code??0;
}
const defaultProfile=()=>({schema:3,selected:15,layer:0,profileIndex:0,performance:Object.fromEntries(keys.map((key)=>[key.id,defaultPerformance()])),keycodes:Object.fromEntries(Array.from({length:4},(_,layerIndex)=>[layerIndex,Object.fromEntries(keys.map((key)=>[key.id,defaultKeycode(key)]))])),lighting:{base:{open:true,openMode:1,mode:1,brightness:80,speed:50,direction:0,paletteIndex:0},palette:["#73f0c0","#70a5ff","#d17cff","#ff7894","#ffc36d","#ffffff","#33bdd0","#587482"],perKey:Object.fromEntries(keys.map((key)=>[key.id,"#73f0c0"]))},settings:{systemMode:0,reportRate:0,sleepTime:10,shake:false}});

function clone(value){return JSON.parse(JSON.stringify(value))}
function esc(value){return String(value??"").replace(/[&<>"']/g,(c)=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function clamp(value,min,max){return Math.max(min,Math.min(max,Number(value)))}
function closeEnough(a,b){return Math.abs(Number(a)-Number(b))<=.0011}
function hexToRgb(hex){const value=String(hex).replace("#","");return{r:parseInt(value.slice(0,2),16),g:parseInt(value.slice(2,4),16),b:parseInt(value.slice(4,6),16),custom:true}}
function rgbToHex(color){return`#${[color.r,color.g,color.b].map((value)=>Number(value||0).toString(16).padStart(2,"0")).join("")}`}
function selectedKey(){return keys.find((key)=>key.id===Number(state.profile.selected))||keys[0]}
function position(key=selectedKey()){return{row:key.row,col:key.col}}
function loadSavedProfile(){const base=defaultProfile();try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY));if(!saved||saved.schema!==3)return base;return{...base,...saved,performance:{...base.performance,...saved.performance},keycodes:Object.fromEntries(Array.from({length:4},(_,i)=>[i,{...base.keycodes[i],...saved.keycodes?.[i]}])),lighting:{...base.lighting,...saved.lighting,base:{...base.lighting.base,...saved.lighting?.base},perKey:{...base.lighting.perKey,...saved.lighting?.perKey}},settings:{...base.settings,...saved.settings}}}catch{return base}}

const state={page:"overview",performanceTab:"trigger",mappingGroup:"keyboard",mappingSearch:"",profile:loadSavedProfile(),original:null,transport:null,translations:clone(FALLBACK_TRANSLATIONS),language:localStorage.getItem(LANGUAGE_KEY)||"en",hardware:{info:null,feature:null,protocol:null,precision:.001,configIndexes:[0,1,2,3],configNames:["Profile 1","Profile 2","Profile 3","Profile 4"],systemModes:[],reportRates:[],axisLibrary:[],lightingAreas:[],customMatrix:null,advanced:null,macroSpace:null,layoutStyle:null,travelValue:0,performance:new Map(),keycodes:new Map(),logs:[]},dirty:{performance:new Set(),mapping:new Set(),lightingBase:false,lightingPalette:false,customLighting:new Set(),settings:new Set()},timers:{travel:null,calibration:null},toastTimer:null};
state.original=clone(state.profile);
const t=(key)=>state.translations[state.language]?.[key]||state.translations.en?.[key]||key;
const connected=()=>Boolean(state.transport?.connected);
const dirtyCount=()=>state.dirty.performance.size+state.dirty.mapping.size+state.dirty.customLighting.size+Number(state.dirty.lightingBase)+Number(state.dirty.lightingPalette)+state.dirty.settings.size;
function log(message,details){state.hardware.logs.unshift({time:new Date().toISOString(),message,...(details===undefined?{}:{details})});state.hardware.logs=state.hardware.logs.slice(0,80)}

async function loadLanguages(){try{const response=await fetch("languages.xml",{cache:"no-store"});if(!response.ok)throw new Error(`HTTP ${response.status}`);const xml=new DOMParser().parseFromString(await response.text(),"application/xml");if(xml.querySelector("parsererror"))throw new Error("Invalid XML");xml.querySelectorAll("language").forEach((language)=>{const code=language.getAttribute("code");if(!code)return;state.translations[code]={...(state.translations[code]||{}),languageName:language.getAttribute("name")||code};language.querySelectorAll("string").forEach((node)=>{state.translations[code][node.getAttribute("key")]=node.textContent})})}catch(error){log("Language XML unavailable; embedded translations used",error.message)}if(!state.translations[state.language])state.language="en";populateLanguageSelectors();translateStaticPage()}
function populateLanguageSelectors(){const html=Object.entries(state.translations).map(([code,strings])=>`<option value="${esc(code)}" ${code===state.language?"selected":""}>${esc(strings.languageName||code)}</option>`).join("");document.querySelectorAll(".language-select").forEach((select)=>{select.innerHTML=html})}
function translateStaticPage(){document.documentElement.lang=state.language;document.querySelectorAll("[data-i18n]").forEach((node)=>{node.textContent=t(node.dataset.i18n)})}
function setLanguage(language){if(!state.translations[language])return;state.language=language;localStorage.setItem(LANGUAGE_KEY,language);populateLanguageSelectors();translateStaticPage();if(!document.querySelector("#workspace").classList.contains("hidden"))render()}

function keyboardHtml({hero=false,lighting=false}={}){const layer=Number(state.profile.layer);return`<div class="keyboard" aria-label="AE64 Pro keyboard">${layout.map((row,uiRow)=>`<div class="keyboard-row">${row.map((_,col)=>{const key=keys.find((candidate)=>candidate.uiRow===uiRow&&candidate.col===col);const code=state.profile.keycodes[layer][key.id];const mapped=KEYCODE_LABELS.get(code)||`0x${Number(code).toString(16).padStart(4,"0")}`;const dirty=state.dirty.performance.has(key.id)||[...state.dirty.mapping].some((token)=>token.endsWith(`:${key.id}`))||state.dirty.customLighting.has(key.id);return`<button class="key ${!hero&&key.id===selectedKey().id?"selected":""} ${dirty?"dirty":""}" style="--u:${key.u};--key-color:${esc(state.profile.lighting.perKey[key.id])}" type="button" ${hero?'tabindex="-1"':`data-key="${key.id}"`}><b>${esc(key.n)}</b>${hero?"":`<span class="mapped">${esc(mapped)}</span>`}${lighting?'<i class="color-dot"></i>':""}</button>`}).join("")}</div>`).join("")}</div>`}
function boardPanel(options={}){return`<section class="panel ${options.full?"full-span":""}"><div class="panel-head"><div><h2>${options.title||"AE64 Pro"}</h2><p>${options.description||"Select a key to inspect or stage a change."}</p></div><span class="badge ${connected()?"ready":""}">${connected()?"HARDWARE":"OFFLINE"}</span></div><div class="keyboard-wrap ${options.lighting?"lighting-preview":""}">${keyboardHtml({lighting:options.lighting})}</div><div class="board-footer"><span>Layer ${Number(state.profile.layer)+1}</span><span>Selected: <b class="selected-name">${esc(selectedKey().n)}</b> · row ${selectedKey().row}, col ${selectedKey().col}</span></div></section>`}
function selectedCard(){const key=selectedKey(),performance=state.profile.performance[key.id],code=state.profile.keycodes[state.profile.layer][key.id];return`<div class="selected-key-card"><b>${esc(key.n)}</b><div><span>SELECTED KEY · ${key.row}:${key.col}</span><strong>${esc(KEYCODE_LABELS.get(code)||`Keycode 0x${Number(code).toString(16)}`)} · ${performance.normalPress.toFixed(2)} mm${performance.mode?" · RT on":""}</strong></div></div>`}
function pageCopy(){return{overview:[t("overview"),"Device state, current profile, and selected-key summary."],performance:[t("performance"),"Per-key Hall actuation, Rapid Trigger, dead zones, calibration, and raw travel."],keymap:[t("keymap"),"Stage assignments across all four firmware layers."],lighting:[t("lighting"),"Base animation, eight-color palette, and per-key custom RGB."],settings:[t("settings"),"Profiles, USB behavior, report rate, sleep, and stabilization."],advanced:[t("featureLab"),"All advanced key modes remain visible, with safe read-only inspection in this basic release."],diagnostics:[t("diagnostics"),"Feature bitmap, device metadata, protocol surface, and session log."]}[state.page]}

function overviewPage(){const perf=state.profile.performance[selectedKey().id],info=state.hardware.info,rtCount=Object.values(state.profile.performance).filter((item)=>item.mode===1).length;return`<div class="page-grid"><section class="panel full-span"><div class="summary-grid"><article class="summary-card"><span>Connection</span><strong>${connected()?"Connected":"Offline"}</strong><small>${connected()?`${esc(info?.serial||"AE64 Pro")} · FW ${esc(info?.firmware||"?")}`:"Demo data; no writes possible"}</small></article><article class="summary-card"><span>Current profile</span><strong>${esc(state.hardware.configNames[state.profile.profileIndex]||`Profile ${state.profile.profileIndex+1}`)}</strong><small>Hardware configuration ${state.profile.profileIndex+1}</small></article><article class="summary-card"><span>Rapid Trigger</span><strong>${rtCount} keys</strong><small>Selected: ${perf.mode?"enabled":"normal"}</small></article><article class="summary-card"><span>Pending changes</span><strong>${dirtyCount()}</strong><small>Written only when you apply</small></article></div></section>${boardPanel()}<section class="panel"><div class="panel-head"><div><h2>Selected key</h2><p>The current working copy for this key.</p></div></div>${selectedCard()}<ul class="fact-list"><li><span>Actuation</span><strong>${perf.normalPress.toFixed(2)} mm</strong></li><li><span>Rapid Trigger</span><strong>${perf.mode?`${perf.rtPress.toFixed(2)} / ${perf.rtRelease.toFixed(2)} mm`:"Off"}</strong></li><li><span>Dead zones</span><strong>${perf.pressDeadStroke.toFixed(2)} / ${perf.releaseDeadStroke.toFixed(2)} mm</strong></li><li><span>Hardware address</span><strong>${selectedKey().row}:${selectedKey().col}</strong></li></ul><div class="apply-row"><button class="button primary" data-goto="performance" type="button">Tune this key</button></div></section></div>`}
function numberField(id,label,value,min,max,step,hint=""){return`<label class="field"><span>${label}</span><div class="range-pair"><input type="range" min="${min}" max="${max}" step="${step}" value="${value}" data-range-for="${id}"><input id="${id}" type="number" min="${min}" max="${max}" step="${step}" value="${value}"></div>${hint?`<small>${hint}</small>`:""}</label>`}
function performanceControls(){const value=state.profile.performance[selectedKey().id];if(state.performanceTab==="trigger")return`${selectedCard()}<div class="switch-row"><div><h3>Rapid Trigger</h3><p>Reset as soon as the key reverses direction.</p></div><input id="performanceMode" class="toggle" type="checkbox" ${value.mode===1?"checked":""}></div><div class="form-grid">${numberField("normalPress","Normal press",value.normalPress,.1,4,.01,"Used when Rapid Trigger is off.")}${numberField("normalRelease","Normal release",value.normalRelease,0,4,.01,"Independent release point.")}${numberField("rtFirstTouch","RT first touch",value.rtFirstTouch,.1,4,.01)}${numberField("rtPress","RT press delta",value.rtPress,.01,2,.01)}${numberField("rtRelease","RT release delta",value.rtRelease,.01,2,.01)}</div><div class="apply-row"><button class="button ghost" data-copy-performance type="button">Copy to every key</button></div>`;if(state.performanceTab==="deadzone")return`${selectedCard()}<div class="form-grid">${numberField("pressDeadStroke","Top dead zone",value.pressDeadStroke,0,1,.01,"Ignored movement near the top.")}${numberField("releaseDeadStroke","Bottom dead zone",value.releaseDeadStroke,0,1,.01,"Ignored movement near full travel.")}</div>`;if(state.performanceTab==="axis")return`${selectedCard()}<ul class="fact-list"><li><span>Axis slot</span><strong>${value.axis}</strong></li><li><span>Axis library ID</span><strong>${value.axisV2Id||"Not reported"}</strong></li><li><span>Maximum range</span><strong>${value.axisRangeMax||"Not reported"}</strong></li><li><span>Coefficient</span><strong>${value.axisCoefficient||"Not reported"}</strong></li><li><span>Available IDs</span><strong>${state.hardware.axisLibrary.length?state.hardware.axisLibrary.join(", "):"Connect to read"}</strong></li></ul><p>The basic release preserves these firmware-owned fields during every performance write.</p>`;if(state.performanceTab==="calibration")return`<div class="panel-head"><div><h2>Hall sensor calibration</h2><p>Start calibration, press every key fully several times, then stop and save.</p></div><span class="badge experimental">DEVICE-WIDE</span></div><div class="calibration-grid">${keys.map(()=>"<i></i>").join("")}</div><div class="apply-row"><button class="button ghost" id="stopCalibration" type="button">Stop</button><button class="button primary" id="startCalibration" type="button">Start calibration</button></div>`;const raw=state.hardware.travelValue||0,mm=Math.min(4,raw/1000);return`${selectedCard()}<div class="travel-meter" style="--travel:${Math.round(mm/4*100)}%;--actuation:${Math.round((1-value.normalPress/4)*100)}%"><div class="fill"></div><div class="line"></div><div class="value">${mm.toFixed(3)} mm</div></div><p>Raw route values are read from the selected physical row.</p><div class="apply-row"><button class="button ghost" id="stopTravel" type="button">Stop</button><button class="button primary" id="startTravel" type="button">Start live reading</button></div>`}
function performancePage(){const tabs=[["trigger","Actuation & RT"],["deadzone","Dead zones"],["axis","Switch axis"],["calibration","Calibration"],["travel","Travel test"]];return`<div class="page-grid">${boardPanel()}<section class="panel"><div class="tab-bar">${tabs.map(([id,label])=>`<button type="button" data-performance-tab="${id}" class="${state.performanceTab===id?"active":""}">${label}</button>`).join("")}</div>${performanceControls()}</section></div>`}
function keymapPage(){const active=state.profile.keycodes[state.profile.layer][selectedKey().id],entries=KEYCODE_GROUPS[state.mappingGroup].filter((entry)=>entry.label.toLowerCase().includes(state.mappingSearch.toLowerCase()));return`<div class="page-grid">${boardPanel()}<section class="panel"><div class="panel-head"><div><h2>Assign ${esc(selectedKey().n)}</h2><p>Writes a 16-bit keycode on layer ${Number(state.profile.layer)+1}.</p></div><span class="badge ready">4 LAYERS</span></div>${selectedCard()}<div class="mapping-browser"><input class="search-input" id="mappingSearch" type="search" placeholder="Search functions" value="${esc(state.mappingSearch)}"><div class="mapping-groups">${Object.keys(KEYCODE_GROUPS).map((group)=>`<button type="button" data-mapping-group="${group}" class="${group===state.mappingGroup?"active":""}">${group}</button>`).join("")}</div><div class="mapping-list">${entries.map((entry)=>`<button type="button" data-keycode="${entry.code}" class="${entry.code===active?"active":""}">${esc(entry.label)}</button>`).join("")}</div></div><div class="apply-row"><button class="button ghost" id="resetKeycode" type="button">Default for this key</button></div></section></div>`}

function lightingPage(){const lighting=state.profile.lighting,base=lighting.base,color=lighting.perKey[selectedKey().id];return`<div class="page-grid">${boardPanel({lighting:true})}<section class="panel"><div class="panel-head"><div><h2>Lighting controls</h2><p>Base effects and the complete 6 × 21 custom matrix.</p></div><span class="badge ready">AREA 0</span></div><div class="switch-row"><div><h3>Main lighting</h3><p>Enable the primary RGB area.</p></div><input id="lightingOpen" class="toggle" type="checkbox" ${base.open?"checked":""}></div><div class="form-grid three"><label class="field"><span>Mode</span><select id="lightingMode">${Array.from({length:16},(_,i)=>`<option value="${i}" ${i===Number(base.mode)?"selected":""}>Effect ${i}</option>`).join("")}</select></label><label class="field"><span>Brightness</span><input id="lightingBrightness" type="number" min="0" max="100" value="${base.brightness}"></label><label class="field"><span>Speed</span><input id="lightingSpeed" type="number" min="0" max="100" value="${base.speed}"></label><label class="field"><span>Direction</span><select id="lightingDirection">${["Forward","Reverse","Left","Right"].map((label,i)=>`<option value="${i}" ${i===Number(base.direction)?"selected":""}>${label}</option>`).join("")}</select></label></div><h3 style="margin-top:20px">Eight-color palette</h3><div class="palette">${lighting.palette.map((swatch,i)=>`<button type="button" data-palette="${i}" class="${i===Number(base.paletteIndex)?"active":""}" style="--swatch:${esc(swatch)}" title="${esc(swatch)}"></button>`).join("")}</div><div class="color-control" style="margin-top:20px"><input id="keyColor" type="color" value="${esc(color)}"><div><h3>Selected-key custom color</h3><p>${esc(selectedKey().n)} · ${esc(color)}. Read the matrix before a connected edit.</p></div></div><div class="apply-row"><button class="button ghost" id="loadCustomLighting" type="button">Read custom matrix</button><button class="button ghost" id="copyKeyColor" type="button">Copy color to all keys</button></div></section></div>`}
function optionList(values,current,prefix){return(values.length?values:[0,1,2,3]).map((value)=>`<option value="${value}" ${Number(value)===Number(current)?"selected":""}>${prefix} ${value}</option>`).join("")}
function settingsPage(){const settings=state.profile.settings;return`<div class="page-grid three"><section class="panel"><div class="panel-head"><div><h2>USB & scanning</h2><p>General firmware settings from the original driver.</p></div></div><div class="form-grid"><label class="field"><span>System mode</span><select id="systemMode">${optionList(state.hardware.systemModes,settings.systemMode,"Mode")}</select></label><label class="field"><span>Report rate</span><select id="reportRate">${optionList(state.hardware.reportRates,settings.reportRate,"Rate")}</select></label><label class="field"><span>RGB sleep (minutes)</span><input id="sleepTime" type="number" min="0" max="65535" value="${settings.sleepTime}"></label></div><div class="switch-row"><div><h3>Shake optimization</h3><p>Firmware key-stability optimization.</p></div><input id="shake" class="toggle" type="checkbox" ${settings.shake?"checked":""}></div></section><section class="panel"><div class="panel-head"><div><h2>Profiles</h2><p>Switch or rename onboard configurations.</p></div></div><label class="field"><span>Profile name</span><input id="profileName" type="text" maxlength="32" value="${esc(state.hardware.configNames[state.profile.profileIndex]||`Profile ${state.profile.profileIndex+1}`)}"></label><div class="apply-row"><button class="button ghost" id="saveProfileName" type="button">Save name</button></div><ul class="fact-list"><li><span>Active slot</span><strong>${state.profile.profileIndex+1}</strong></li><li><span>Available slots</span><strong>${state.hardware.configIndexes.length}</strong></li></ul></section><section class="panel"><div class="panel-head"><div><h2>Files & recovery</h2><p>Portable JSON, independent of the manufacturer cloud.</p></div></div><div class="apply-row"><button class="button ghost" id="importProfile" type="button">Import JSON</button><button class="button primary" id="exportProfile" type="button">Export JSON</button></div><hr style="border:0;border-top:1px solid var(--line);margin:22px 0"><h3>Factory restore</h3><p>This destructive command stays visible but disabled until physical-device verification.</p><button class="button danger" type="button" disabled>Restore factory settings</button></section></div>`}
const ADVANCED_FEATURES=[["DKS","Dynamic Keystroke","Up to four keycodes at multiple press/release points."],["MPT","Multi-point Trigger","Three key actions at distinct travel depths."],["MT","Mod-Tap","Tap one function and hold another after a time threshold."],["TGL","Toggle Key","Latch a key action with firmware timing."],["END","End Key","Trigger paired actions with an end delay."],["SOCD","SOCD Resolution","Resolve two opposing keys using firmware priority modes."],["RS","Rappy Snappy","Compare two keys by travel and prefer the deeper input."]];
function advancedPage(){return`<div class="page-grid"><section class="panel full-span warning-card"><div class="panel-head"><div><h2>Advanced Hall-key modes</h2><p>All seven shipped features are visible. This basic release safely decodes them without unverified writes.</p></div><span class="badge experimental">VISIBLE · READ ONLY</span></div></section>${boardPanel()}<section class="panel"><div class="panel-head"><div><h2>Selected-key record</h2><p>Decoded directly from family 0x06.</p></div></div>${selectedCard()}<div class="apply-row"><button class="button ghost" id="readMacroSpace" type="button">Read macro capacity</button><button class="button primary" id="readAdvanced" type="button">Read advanced record</button></div><pre class="raw-output">${esc(JSON.stringify({advanced:state.hardware.advanced||"Connect and read",macroSpace:state.hardware.macroSpace||"Not read"},null,2))}</pre></section><section class="panel full-span"><div class="advanced-grid">${ADVANCED_FEATURES.map(([code,title,body],i)=>`<article class="advanced-card"><header><h3>${code}</h3><span class="badge deferred">EDITOR NEXT</span></header><strong>${title}</strong><p>${body}</p><small>family 06 · mode ${i+1}</small></article>`).join("")}</div></section></div>`}
function capabilityCards(){const feature=state.hardware.feature;const known={mechanical:null,magnetic:null,optical:null,inductive:null,magnetic3D:null,usb:null,wireless24:null,bluetooth:null,usb3:null,rgb:null,knob:null,smallScreen:null,fullScreen:null,haptic:null,voicePlayback:null,voiceRecognition:null,gamepad:null,dotMatrix:null};if(feature)Object.assign(known,feature.axis,feature.connection,feature.basic,feature.extended);return`<div class="capability-grid">${Object.entries(known).map(([name,enabled])=>`<article class="capability ${enabled===true?"yes":"no"}"><span>${esc(name)}</span><strong>${enabled===null?"Connect to detect":enabled?"Reported":"Not reported"}</strong></article>`).join("")}</div>`}
function diagnosticsPage(){const info=state.hardware.info||{};return`<div class="page-grid"><section class="panel"><div class="panel-head"><div><h2>Device identity</h2><p>Configuration HID collection metadata.</p></div><span class="badge ${connected()?"ready":""}">${connected()?"LIVE":"DEMO"}</span></div><ul class="fact-list"><li><span>VID:PID</span><strong>1CA6:300A</strong></li><li><span>Board ID</span><strong>${esc(info.boardIdHex||"0030000A expected")}</strong></li><li><span>Firmware</span><strong>${esc(info.firmware||"Connect to read")}</strong></li><li><span>Protocol</span><strong>${state.hardware.protocol?`${state.hardware.protocol.main}.${state.hardware.protocol.sub}`:"Connect to read"}</strong></li><li><span>Serial</span><strong>${esc(info.serial||"Connect to read")}</strong></li><li><span>RT precision</span><strong>${Number(state.hardware.precision||.001).toFixed(3)} mm</strong></li></ul><div class="apply-row"><button class="button ghost" id="readLayoutStyle" type="button">Read layout metadata</button><button class="button ghost" id="exportLog" type="button">Export session log</button></div></section><section class="panel"><div class="panel-head"><div><h2>Firmware capabilities</h2><p>Hidden generic features remain visible even when their bit is off.</p></div></div>${capabilityCards()}</section><section class="panel full-span"><div class="panel-head"><div><h2>Supported protocol surface</h2><p>Firmware upgrade and bootloader commands are intentionally absent.</p></div><span class="badge ready">NO UPDATER</span></div><div class="capability-grid">${["Device identity","Profiles","System settings","Four key layers","Hall performance","Raw axis data","Base RGB","Custom RGB","Advanced key reads","Macro reads","Calibration","Read-back verify"].map((name)=>`<article class="capability yes"><span>Available</span><strong>${name}</strong></article>`).join("")}</div><pre class="raw-output">${esc(JSON.stringify({layoutStyle:state.hardware.layoutStyle,recent:state.hardware.logs.slice(0,12)},null,2))}</pre></section></div>`}

function render(){stopPolling();const [title,description]=pageCopy();document.querySelector("#pageKicker").textContent=`AE64 PRO / ${state.page.toUpperCase()}`;document.querySelector("#pageTitle").textContent=title;document.querySelector("#pageDescription").textContent=description;document.querySelectorAll("#sideNav button").forEach((button)=>button.classList.toggle("active",button.dataset.page===state.page));const pages={overview:overviewPage,performance:performancePage,keymap:keymapPage,lighting:lightingPage,settings:settingsPage,advanced:advancedPage,diagnostics:diagnosticsPage};document.querySelector("#pageContent").innerHTML=pages[state.page]();renderToolbar();renderStatus();bindPage()}
function renderToolbar(){document.querySelector("#profileSelect").innerHTML=state.hardware.configIndexes.map((index)=>`<option value="${index}" ${index===Number(state.profile.profileIndex)?"selected":""}>${esc(state.hardware.configNames[index]||`Profile ${index+1}`)}</option>`).join("");document.querySelector("#layerSelect").value=String(state.profile.layer);document.querySelectorAll(".language-select").forEach((select)=>{select.value=state.language})}
function renderStatus(){const count=dirtyCount();document.querySelector("#connectionStatus").textContent=connected()?`Connected · FW ${state.hardware.info?.firmware||"?"}`:t("offline");document.querySelector("#connectionDot").className=connected()?"":"offline";document.querySelector("#dirtyStatus").textContent=count?`${count} staged change${count===1?"":"s"}`:t("noPendingChanges");document.querySelector("#applyButton").disabled=count===0;document.querySelector("#revertButton").disabled=count===0;document.querySelector("#connectionLabel").textContent=connected()?`Connected · FW ${state.hardware.info?.firmware||"?"}`:t("offlineWorkspace")}
function stagePerformance(field,value){state.profile.performance[selectedKey().id][field]=value;state.dirty.performance.add(selectedKey().id);renderStatus()}
function stageSetting(field,value){state.profile.settings[field]=value;state.dirty.settings.add(field);renderStatus()}
function bindNumberPair(id,field){const number=document.querySelector(`#${id}`),range=document.querySelector(`[data-range-for="${id}"]`);if(!number||!range)return;const update=(source,other)=>{const value=clamp(source.value,Number(source.min),Number(source.max));other.value=value;stagePerformance(field,value)};number.addEventListener("input",()=>update(number,range));range.addEventListener("input",()=>update(range,number))}

function bindPage(){
  document.querySelectorAll("[data-key]").forEach((button)=>button.addEventListener("click",()=>selectKey(Number(button.dataset.key))));document.querySelectorAll("[data-goto]").forEach((button)=>button.addEventListener("click",()=>{state.page=button.dataset.goto;render()}));document.querySelectorAll("[data-performance-tab]").forEach((button)=>button.addEventListener("click",()=>{state.performanceTab=button.dataset.performanceTab;render()}));
  if(state.page==="performance"){document.querySelector("#performanceMode")?.addEventListener("change",(event)=>stagePerformance("mode",event.target.checked?1:0));["normalPress","normalRelease","rtFirstTouch","rtPress","rtRelease","pressDeadStroke","releaseDeadStroke"].forEach((field)=>bindNumberPair(field,field));document.querySelector("[data-copy-performance]")?.addEventListener("click",()=>{const source=clone(state.profile.performance[selectedKey().id]);keys.forEach((key)=>{state.profile.performance[key.id]=clone(source);state.dirty.performance.add(key.id)});render();showToast("Performance settings staged for all 64 keys.")});document.querySelector("#startCalibration")?.addEventListener("click",startCalibration);document.querySelector("#stopCalibration")?.addEventListener("click",stopCalibration);document.querySelector("#startTravel")?.addEventListener("click",startTravel);document.querySelector("#stopTravel")?.addEventListener("click",stopPolling)}
  if(state.page==="keymap"){document.querySelector("#mappingSearch")?.addEventListener("input",(event)=>{state.mappingSearch=event.target.value;render();document.querySelector("#mappingSearch")?.focus()});document.querySelectorAll("[data-mapping-group]").forEach((button)=>button.addEventListener("click",()=>{state.mappingGroup=button.dataset.mappingGroup;state.mappingSearch="";render()}));document.querySelectorAll("[data-keycode]").forEach((button)=>button.addEventListener("click",()=>{const token=`${state.profile.layer}:${selectedKey().id}`;state.profile.keycodes[state.profile.layer][selectedKey().id]=Number(button.dataset.keycode);state.dirty.mapping.add(token);render()}));document.querySelector("#resetKeycode")?.addEventListener("click",()=>{state.profile.keycodes[state.profile.layer][selectedKey().id]=defaultKeycode(selectedKey());state.dirty.mapping.add(`${state.profile.layer}:${selectedKey().id}`);render()})}
  if(state.page==="lighting"){const fields={lightingOpen:["open",(element)=>element.checked],lightingMode:["mode",(element)=>Number(element.value)],lightingBrightness:["brightness",(element)=>clamp(element.value,0,100)],lightingSpeed:["speed",(element)=>clamp(element.value,0,100)],lightingDirection:["direction",(element)=>Number(element.value)]};Object.entries(fields).forEach(([id,[field,read]])=>document.querySelector(`#${id}`)?.addEventListener("change",(event)=>{state.profile.lighting.base[field]=read(event.target);state.dirty.lightingBase=true;renderStatus()}));document.querySelectorAll("[data-palette]").forEach((button)=>button.addEventListener("click",()=>{state.profile.lighting.base.paletteIndex=Number(button.dataset.palette);state.dirty.lightingBase=true;render()}));document.querySelector("#keyColor")?.addEventListener("input",(event)=>{state.profile.lighting.perKey[selectedKey().id]=event.target.value;state.dirty.customLighting.add(selectedKey().id);renderStatus()});document.querySelector("#loadCustomLighting")?.addEventListener("click",loadCustomLighting);document.querySelector("#copyKeyColor")?.addEventListener("click",()=>{const color=state.profile.lighting.perKey[selectedKey().id];keys.forEach((key)=>{state.profile.lighting.perKey[key.id]=color;state.dirty.customLighting.add(key.id)});render()})}
  if(state.page==="settings"){document.querySelector("#systemMode")?.addEventListener("change",(event)=>stageSetting("systemMode",Number(event.target.value)));document.querySelector("#reportRate")?.addEventListener("change",(event)=>stageSetting("reportRate",Number(event.target.value)));document.querySelector("#sleepTime")?.addEventListener("change",(event)=>stageSetting("sleepTime",clamp(event.target.value,0,65535)));document.querySelector("#shake")?.addEventListener("change",(event)=>stageSetting("shake",event.target.checked));document.querySelector("#saveProfileName")?.addEventListener("click",saveProfileName);document.querySelector("#exportProfile")?.addEventListener("click",exportProfile);document.querySelector("#importProfile")?.addEventListener("click",()=>document.querySelector("#profileFileInput").click())}
  if(state.page==="advanced"){document.querySelector("#readAdvanced")?.addEventListener("click",readAdvanced);document.querySelector("#readMacroSpace")?.addEventListener("click",readMacroSpace)}if(state.page==="diagnostics"){document.querySelector("#readLayoutStyle")?.addEventListener("click",readLayoutStyle);document.querySelector("#exportLog")?.addEventListener("click",exportLog)}
}

async function selectKey(id){state.profile.selected=id;render();if(!connected())return;try{await readSelectedKey();if(selectedKey().id===id)render()}catch(error){showToast(error.message,true)}}
function openWorkspace(){document.querySelector("#topbar").classList.add("hidden");document.querySelector("main").classList.add("hidden");document.querySelector("#workspace").classList.remove("hidden");render();window.scrollTo({top:0})}
function returnHome(){stopPolling();document.querySelector("#workspace").classList.add("hidden");document.querySelector("#topbar").classList.remove("hidden");document.querySelector("main").classList.remove("hidden");window.scrollTo({top:0,behavior:"smooth"})}
function showToast(message,isError=false){const node=document.querySelector("#toast");node.textContent=message;node.classList.toggle("error",isError);node.classList.add("show");clearTimeout(state.toastTimer);state.toastTimer=setTimeout(()=>node.classList.remove("show"),3600)}
function showProgress(title,detail=""){document.querySelector("#progressTitle").textContent=title;document.querySelector("#progressDetail").textContent=detail;document.querySelector("#progressOverlay").classList.remove("hidden")}
function hideProgress(){document.querySelector("#progressOverlay").classList.add("hidden")}
async function optional(label,operation,fallback=null){try{return await operation()}catch(error){log(`${label} unavailable`,error.message);return fallback}}

async function connectKeyboard(){showProgress("Connecting to AE64 Pro","Choose the 1CA6:300A configuration interface.");try{if(state.transport)await state.transport.close();state.transport=await AE64HidTransport.request();await optional("open-web-driver handshake",()=>state.transport.openWebDriver());const [protocol,info,feature,precision,configIndexes,currentConfig,systemModes,systemMode,reportRates,reportRate,sleepTime,shake,axisLibrary,lightingAreas,lightingBase,palette]=await Promise.all([state.transport.getProtocolVersion(),state.transport.getDeviceInfo(),state.transport.getDeviceFeature(),state.transport.getRtPrecision(),optional("config list",()=>state.transport.getConfigList(),[0,1,2,3]),optional("current config",()=>state.transport.getCurrentConfig(),0),optional("system modes",()=>state.transport.getSystemModes(),[]),optional("system mode",()=>state.transport.getSystemMode(),0),optional("report rates",()=>state.transport.getReportRates(),[]),optional("report rate",()=>state.transport.getReportRate(),0),optional("lighting sleep",()=>state.transport.getLightingSleepTime(),10),optional("shake optimization",()=>state.transport.getShakeOptimization(),false),optional("axis library",()=>state.transport.getAxisLibrary(),[]),optional("lighting areas",()=>state.transport.getLightingAreas(),[]),optional("lighting base",()=>state.transport.getLightingBase(0),state.profile.lighting.base),optional("lighting palette",()=>state.transport.getLightingPalette(0),null)]);if(info.boardIdHex.toUpperCase()!=="0030000A")throw new Error(`Unexpected board ID ${info.boardIdHex}; writes refused.`);Object.assign(state.hardware,{protocol,info,feature,precision,configIndexes:configIndexes.length?configIndexes:[0,1,2,3],systemModes,reportRates,axisLibrary,lightingAreas});state.profile.profileIndex=currentConfig;state.profile.settings={systemMode,reportRate,sleepTime,shake};state.profile.lighting.base={...state.profile.lighting.base,...lightingBase};if(palette)state.profile.lighting.palette=palette.map(rgbToHex);state.hardware.configNames=await Promise.all(state.hardware.configIndexes.map((index)=>optional(`profile ${index+1} name`,()=>state.transport.getConfigName(index),`Profile ${index+1}`)));await readSelectedKey();state.original=clone(state.profile);clearDirty();log("Connected",{boardId:info.boardIdHex,firmware:info.firmware,protocol});openWorkspace();showToast(`AE64 Pro connected · firmware ${info.firmware}`)}catch(error){log("Connection failed",error.message);if(state.transport)await state.transport.close().catch(()=>undefined);state.transport=null;showToast(`Could not connect: ${error.message}`,true);renderStatus()}finally{hideProgress()}}
async function readSelectedKey(){if(!connected())return;const key=selectedKey(),token=`${state.profile.layer}:${key.id}`;const [performance,keyRecord]=await Promise.all([state.transport.getPerformance(position(key)),state.transport.getKeyCode(position(key),state.profile.layer)]);state.hardware.performance.set(key.id,performance);state.hardware.keycodes.set(token,keyRecord.keycode);if(!state.dirty.performance.has(key.id))state.profile.performance[key.id]=performance;if(!state.dirty.mapping.has(token))state.profile.keycodes[state.profile.layer][key.id]=keyRecord.keycode;log("Selected key read",{key:key.n,row:key.row,col:key.col,layer:state.profile.layer})}
function clearDirty(){state.dirty.performance.clear();state.dirty.mapping.clear();state.dirty.customLighting.clear();state.dirty.settings.clear();state.dirty.lightingBase=false;state.dirty.lightingPalette=false}
function verifyPerformance(expected,actual){return["mode","normalPress","normalRelease","rtFirstTouch","rtPress","rtRelease","pressDeadStroke","releaseDeadStroke"].every((field)=>field==="mode"?Number(expected[field])===Number(actual[field]):closeEnough(expected[field],actual[field]))}

async function applyChanges(){if(!dirtyCount())return;localStorage.setItem(STORAGE_KEY,JSON.stringify(state.profile));if(!connected()){state.original=clone(state.profile);clearDirty();render();showToast("Workspace saved in this browser. Connect to write it to the keyboard.");return}showProgress("Applying staged changes","Reading existing records and preserving firmware-owned fields.");try{const performanceIds=[...state.dirty.performance];for(let index=0;index<performanceIds.length;index+=1){const id=performanceIds[index],key=keys[id];document.querySelector("#progressDetail").textContent=`Performance ${index+1} of ${performanceIds.length}: ${key.n}`;const current=state.hardware.performance.get(id)||await state.transport.getPerformance(position(key));const desired={...current,...state.profile.performance[id],axis:current.axis,calibrate:current.calibrate,axisV2Id:current.axisV2Id,axisRangeMax:current.axisRangeMax,axisCoefficient:current.axisCoefficient};await state.transport.setPerformance(position(key),desired);const verified=await state.transport.getPerformance(position(key));if(!verifyPerformance(desired,verified))throw new Error(`Performance verification failed for ${key.n}.`);state.profile.performance[id]=verified;state.hardware.performance.set(id,verified)}if(performanceIds.length)await state.transport.saveParameters(SAVE_GROUP.PERFORMANCE);
    const mappingTokens=[...state.dirty.mapping];for(let index=0;index<mappingTokens.length;index+=1){const [layer,id]=mappingTokens[index].split(":").map(Number),key=keys[id],expected=state.profile.keycodes[layer][id];document.querySelector("#progressDetail").textContent=`Key mapping ${index+1} of ${mappingTokens.length}: ${key.n}`;await state.transport.setKeyCode(position(key),expected,layer);const verified=await state.transport.getKeyCode(position(key),layer);if(verified.keycode!==expected)throw new Error(`Mapping verification failed for ${key.n}.`);state.hardware.keycodes.set(`${layer}:${id}`,expected)}if(mappingTokens.length)await state.transport.saveParameters(SAVE_GROUP.LAYOUT);
    if(state.dirty.lightingBase||state.dirty.lightingPalette){if(state.dirty.lightingBase){await state.transport.setLightingBase(state.profile.lighting.base,0);const verified=await state.transport.getLightingBase(0);for(const field of["open","mode","brightness","speed","direction","paletteIndex"])if(Number(verified[field])!==Number(state.profile.lighting.base[field]))throw new Error(`Lighting ${field} verification failed.`);state.profile.lighting.base={...state.profile.lighting.base,...verified}}if(state.dirty.lightingPalette)await state.transport.setLightingPalette(state.profile.lighting.palette.map(hexToRgb),0);await state.transport.saveParameters(SAVE_GROUP.LIGHTING)}
    if(state.dirty.customLighting.size){if(!state.hardware.customMatrix)state.hardware.customMatrix=await state.transport.readCustomLighting(MATRIX_ROWS,MATRIX_COLS,0);for(const id of state.dirty.customLighting){const key=keys[id];state.hardware.customMatrix[key.row*MATRIX_COLS+key.col]=hexToRgb(state.profile.lighting.perKey[id])}await state.transport.writeCustomLighting(state.hardware.customMatrix,MATRIX_ROWS,MATRIX_COLS,0);await state.transport.saveParameters(SAVE_GROUP.LIGHTING);const id=[...state.dirty.customLighting][0],key=keys[id],matrixIndex=key.row*MATRIX_COLS+key.col,packet=await state.transport.getCustomLightingPacket(Math.floor(matrixIndex/15),0);if(rgbToHex(packet[matrixIndex%15])!==state.profile.lighting.perKey[id].toLowerCase())throw new Error(`Custom lighting verification failed for ${key.n}.`)}
    for(const field of state.dirty.settings){if(field==="systemMode")await state.transport.setSystemMode(state.profile.settings[field]);if(field==="reportRate")await state.transport.setReportRate(state.profile.settings[field]);if(field==="sleepTime")await state.transport.setLightingSleepTime(state.profile.settings[field]);if(field==="shake")await state.transport.setShakeOptimization(state.profile.settings[field])}state.original=clone(state.profile);clearDirty();localStorage.setItem(STORAGE_KEY,JSON.stringify(state.profile));log("Staged changes applied and verified");render();showToast("Changes written, committed, and verified on the AE64 Pro.")}catch(error){log("Apply failed",error.message);renderStatus();showToast(`Apply stopped: ${error.message}`,true)}finally{hideProgress()}}

function revertChanges(){state.profile=clone(state.original);clearDirty();render();showToast("Staged changes reverted.")}
async function switchProfile(index){if(dirtyCount()){showToast("Apply or revert changes before switching profiles.",true);renderToolbar();return}if(connected()){showProgress("Switching profile",`Loading profile ${index+1}.`);try{await state.transport.switchConfig(index);state.profile.profileIndex=index;await readSelectedKey();state.original=clone(state.profile);log("Profile switched",index);showToast(`Profile ${index+1} loaded.`)}catch(error){showToast(error.message,true)}finally{hideProgress();render()}}else{state.profile.profileIndex=index;state.original=clone(state.profile);render()}}
async function saveProfileName(){const name=document.querySelector("#profileName").value.trim();if(!name)return showToast("Profile name cannot be empty.",true);if(!connected())return showToast("Connect to rename an onboard profile.",true);try{await state.transport.setConfigName(state.profile.profileIndex,name);const verified=await state.transport.getConfigName(state.profile.profileIndex);state.hardware.configNames[state.profile.profileIndex]=verified;render();showToast(`Profile renamed to ${verified}.`)}catch(error){showToast(error.message,true)}}
async function loadCustomLighting(){if(!connected())return showToast("Connect to read custom RGB.",true);showProgress("Reading custom lighting","Loading all nine matrix packets.");try{state.hardware.customMatrix=await state.transport.readCustomLighting(MATRIX_ROWS,MATRIX_COLS,0);keys.forEach((key)=>{state.profile.lighting.perKey[key.id]=rgbToHex(state.hardware.customMatrix[key.row*MATRIX_COLS+key.col])});state.dirty.customLighting.clear();render();showToast("Custom lighting matrix loaded.")}catch(error){showToast(error.message,true)}finally{hideProgress()}}
async function readAdvanced(){if(!connected())return showToast("Connect to read the advanced-key record.",true);try{state.hardware.advanced=await state.transport.getAdvancedKey(position());log("Advanced record read",state.hardware.advanced);render()}catch(error){showToast(error.message,true)}}
async function readMacroSpace(){if(!connected())return showToast("Connect to read macro capacity.",true);try{state.hardware.macroSpace=await state.transport.getMacroSpaceInfo();log("Macro capacity read",state.hardware.macroSpace);render()}catch(error){showToast(error.message,true)}}
async function readLayoutStyle(){if(!connected())return showToast("Connect to read layout metadata.",true);try{state.hardware.layoutStyle=await Promise.all([1,2,3,4,5].map((row)=>state.transport.getKeyLayoutStyle(row)));log("Layout metadata read");render()}catch(error){showToast(error.message,true)}}
async function startCalibration(){if(!connected())return showToast("Connect before calibration.",true);try{await state.transport.setCalibration(true);log("Calibration started");showToast("Calibration active. Press every key fully several times.");let cursor=0;const cells=[...document.querySelectorAll(".calibration-grid i")];state.timers.calibration=setInterval(()=>{cells.slice(0,cursor+=2).forEach((cell)=>cell.classList.add("done"))},250)}catch(error){showToast(error.message,true)}}
async function stopCalibration(){if(state.timers.calibration)clearInterval(state.timers.calibration);state.timers.calibration=null;if(!connected())return;try{await state.transport.setCalibration(false);await state.transport.saveParameters(SAVE_GROUP.CALIBRATION);log("Calibration stopped and saved");showToast("Calibration stopped and saved.")}catch(error){showToast(error.message,true)}}
async function startTravel(){if(!connected())return showToast("Connect to read live travel.",true);stopPolling();const read=async()=>{if(!connected()||state.page!=="performance"||state.performanceTab!=="travel")return;try{const key=selectedKey(),data=await state.transport.getAxisData("route",key.row);state.hardware.travelValue=data.values[key.col]||0;const valueNode=document.querySelector(".travel-meter .value"),meter=document.querySelector(".travel-meter");if(valueNode&&meter){const mm=Math.min(4,state.hardware.travelValue/1000);valueNode.textContent=`${mm.toFixed(3)} mm`;meter.style.setProperty("--travel",`${Math.round(mm/4*100)}%`)}}catch(error){log("Travel poll stopped",error.message);showToast(error.message,true);return}state.timers.travel=setTimeout(read,120)};read()}
function stopPolling(){if(state.timers.travel)clearTimeout(state.timers.travel);state.timers.travel=null}

function downloadJson(filename,value){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:"application/json"})),link=document.createElement("a");link.href=url;link.download=filename;link.click();setTimeout(()=>URL.revokeObjectURL(url),0)}
function exportProfile(){downloadJson("ae64-pro-profile.json",{format:"ae64-control-profile",version:1,device:{vendorId:"1CA6",productId:"300A"},exportedAt:new Date().toISOString(),profile:state.profile});showToast("Profile exported.")}
function exportLog(){downloadJson("ae64-pro-session-log.json",{device:state.hardware.info,logs:state.hardware.logs});showToast("Session log exported.")}
async function importProfile(file){try{const data=JSON.parse(await file.text()),imported=data.profile||data;if(!imported.performance||!imported.keycodes||!imported.lighting)throw new Error("Not an AE64 Control profile.");const base=defaultProfile();state.profile={...base,...imported,schema:3,performance:{...base.performance,...imported.performance},keycodes:Object.fromEntries(Array.from({length:4},(_,i)=>[i,{...base.keycodes[i],...imported.keycodes?.[i]}])),lighting:{...base.lighting,...imported.lighting,base:{...base.lighting.base,...imported.lighting.base},perKey:{...base.lighting.perKey,...imported.lighting.perKey}}};keys.forEach((key)=>{state.dirty.performance.add(key.id);state.dirty.customLighting.add(key.id);for(let layer=0;layer<4;layer+=1)state.dirty.mapping.add(`${layer}:${key.id}`)});state.dirty.lightingBase=true;state.dirty.lightingPalette=true;render();showToast("Profile imported and staged. Review before applying.")}catch(error){showToast(`Import failed: ${error.message}`,true)}}
function mountHero(){document.querySelector("#heroKeyboard").innerHTML=keyboardHtml({hero:true})}

document.querySelectorAll("#connectButton,#heroConnect,#workspaceConnectButton").forEach((button)=>button.addEventListener("click",connectKeyboard));
document.querySelectorAll("#demoButton,#heroDemo").forEach((button)=>button.addEventListener("click",openWorkspace));
document.querySelector("#backHomeButton").addEventListener("click",returnHome);
document.querySelector("#applyButton").addEventListener("click",applyChanges);
document.querySelector("#revertButton").addEventListener("click",revertChanges);
document.querySelector("#sideNav").addEventListener("click",(event)=>{const button=event.target.closest("button[data-page]");if(button){state.page=button.dataset.page;render()}});
document.querySelector("#profileSelect").addEventListener("change",(event)=>switchProfile(Number(event.target.value)));
document.querySelector("#layerSelect").addEventListener("change",async(event)=>{state.profile.layer=Number(event.target.value);render();if(connected())try{await readSelectedKey();render()}catch(error){showToast(error.message,true)}});
document.querySelectorAll(".language-select").forEach((select)=>select.addEventListener("change",(event)=>setLanguage(event.target.value)));
document.querySelector("#profileFileInput").addEventListener("change",(event)=>{const[file]=event.target.files;if(file)importProfile(file);event.target.value=""});
if(navigator.hid)navigator.hid.addEventListener("disconnect",(event)=>{if(event.device===state.transport?.device){state.transport=null;stopPolling();log("Keyboard disconnected");renderStatus();showToast("AE64 Pro disconnected.",true)}});
mountHero();
loadLanguages();
